// Generates website/static/llms-full.txt — the full text of the canonical docs
// concatenated into a single file, served verbatim at /llms-full.txt (the
// "give me everything" companion to the hand-curated /llms.txt index).
//
// Source of truth is repo-root docs/, mirroring the docs plugin's include rule
// in docusaurus.config.ts (intro.md, adopters/**, contributors/**). The output
// is a generated artifact (gitignored) and is regenerated by prestart/prebuild,
// exactly like scripts/sync-docs-i18n.ts.
import {readdirSync, readFileSync, writeFileSync, statSync} from 'node:fs';
import {join, resolve} from 'node:path';
import matter from 'gray-matter';

const ROOT = resolve(__dirname, '..');
const DOCS = resolve(ROOT, '../docs');
const OUT = join(ROOT, 'static', 'llms-full.txt');
const SITE_URL = 'https://straymark.dev';

// Directories under docs/ to walk, in output order. intro.md is handled first
// and separately (it carries `slug: /`). decisions/ and proposals/ are excluded
// by omission — they live outside these two dirs.
const DIRS = ['adopters', 'contributors'];

/** Recursively collect *.md files under `dir`, returned sorted for stable output. */
function collectMarkdown(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...collectMarkdown(full));
    } else if (entry.endsWith('.md')) {
      out.push(full);
    }
  }
  return out.sort();
}

/** Map an absolute doc path to its public Docusaurus route (trailingSlash: false). */
function routeFor(absPath: string): string {
  const rel = absPath.slice(DOCS.length + 1).replace(/\.md$/, '');
  if (rel === 'intro') return `${SITE_URL}/docs`; // slug: / → docs root
  // README.md / index.md become the directory index route.
  const asIndex = rel.replace(/\/(README|index)$/, '');
  if (asIndex !== rel) return `${SITE_URL}/docs/${asIndex}`;
  return `${SITE_URL}/docs/${rel}`;
}

/** Title from frontmatter `title`, else first `# H1`, else the filename. */
function titleFor(absPath: string, data: Record<string, unknown>, body: string): string {
  if (typeof data.title === 'string' && data.title.trim()) return data.title.trim();
  const h1 = body.match(/^#\s+(.+)$/m);
  if (h1) return h1[1].trim();
  return absPath.slice(DOCS.length + 1).replace(/\.md$/, '');
}

// Ordered file list: intro first, then each configured dir.
const files = [join(DOCS, 'intro.md'), ...DIRS.flatMap((d) => collectMarkdown(join(DOCS, d)))];

const sections: string[] = [
  '# StrayMark — Full Documentation',
  '',
  '> The complete text of the StrayMark adopter and contributor documentation,',
  '> concatenated for LLM consumption. The curated index lives at /llms.txt.',
  '> Canonical source: https://github.com/StrangeDaysTech/straymark/tree/main/docs',
  '',
];

for (const file of files) {
  const raw = readFileSync(file, 'utf8');
  const {content, data} = matter(raw);
  const title = titleFor(file, data, content);
  const url = routeFor(file);
  sections.push('---', '', `## ${title}`, '', `Source: ${url}`, '', content.trim(), '');
}

writeFileSync(OUT, sections.join('\n') + '\n');
console.log(`[gen-llms-full] wrote ${OUT} (${files.length} docs)`);
