import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Adopters',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'adopters'}],
    },
    {
      type: 'category',
      label: 'Contributors',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'contributors'}],
    },
    {
      type: 'category',
      label: 'Decisions',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'decisions'}],
    },
  ],
};

export default sidebars;
